### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by bebusl** [bebusl/Industrial-Project#1]
산학 프로젝트 주제 선정을 위한 의견 공유

**Comment by bebusl** [comment]
**벽지에 따른 가구 색(인테리어 테마) 추천 서비스**
  - 월세로 사는 경우 벽지를 원하는 색으로 바꾸기가 힘듦
  - 이 경우 인테리어 구성을 생각하기가 쉽지 않을 수 있는데, 전반적인 테마나 가구 색을 추천해주면 좀 더 수월하게 가구를 선택하고 인테리어를 설계하는데 도움이 될 것이라고 생각됨.

**영양제 추천 서비스** 
 - 시중 많은 영양제 추천 서비스가 있으나 기존 먹던 영양제를 함께 고려해서 추천해주는 서비스는 보지 못했음.
 - 기존에 먹던 영양제를 포함해서 사용자에게 필요한 영양제를 추천해주면 좋을 것이라고 생각됨.

**Comment by dungbik** [comment]
구매자 리뷰 기반 상품 추천 시스템

- 상품을 구매할 때 리뷰를 하나하나 읽어보기 힘듦
- 리뷰에서 키워드를 추출하여 사용자가 선호/불호 키워드를 선택하게 하여 이를 기반으로 상품을 추천

교양 강의 추천 시스템 

- 자신이 원하는 강의를 찾기가 쉽지 않음
- 수강한 강의 만족도/학점, 선호/불호 tag, 다른 사용자의 수강 내역, 강의 tag를 이용한 추천

**Comment by leejeongeun0** [comment]
**식사 메뉴 추천 서비스**

1. 문제
매일 '오늘 뭐먹지?' 고민하느라 많은 시간을 보내는 사람, 좋은 사람과 좋은 곳에서 식사하고싶은데 주변 음식점을 잘 모르는 사람, 직장에서 매일 센스있는 식사 메뉴를 이야기해야하는 사람. 
2. 해결방법
 날씨, 지역, 시간은 입력하지 않아도 사용자 동의만있으면 정보를 수집 할 수 있도록. (직접 검색도 가능)
 식사 인원과 관계 (친구, 연인, 직장동료, 가족 등), 연령대를 입력하면 추천 메뉴 3순위까지 출력.

사회생활이 필요한 직장인들과 좋은 사람과 좋은 곳에 가고싶은 사람들, 
 매일 메뉴고민에 힘든사람들에게 시간적 비용과 심리적 부담을 줄여주는 서비스 제공 가능.
