### ISSUE TITLE
프로그램 개발 방향 (요구사항 정의서)

### ISSUE THREAD

**Issue by leejeongeun0** [bebusl/Industrial-Project#10]
1. 서 론
1.1 문서 목적 및 범위
1.2 대상 시스템 개요 
1.2.1 대상 시스템 정의
해당 시스템, 연관 키워드 기반 도서 추천 서비스는 사용자의 기분과 취향 등을 나타내는 키워드에 밀접하게 연관된 도서를 추천해주는 안드로이드 기반 앱이다.
1.2.2 주요 기능 설명    
1)사용자에게 입력받은 키워드를 이용하여 도서를 추천한다.
사용자에게 원하는 장르나 취향의 키워드를 입력하게한다. 입력된 키워드는 TF-IDF를 이용해 유사한 키워드를 추출하고 본 키워드와 데이터 베이스에 저장해놓은 정보를 비교하여 연관성이 높은 도서를 사용자에게 추천한다.
2)사용자는 입력한 키워드와 연관있는 키워드들의 선호도를 체크할 수 있다.
입력한 키워드의 유사 키워드를 추출하였을 때, 사용자의 의도와 맞지 않은 키워드가 선별될 수 있으므로 사용자가 선호 키워드를 직접 선택할 수 있게하여 추천 서비스의 정확도와 만족감을 높인다.

2. 기능적 요구사항  
2-1 도서 추천 서비스 이용 관련 기능 - WF
**WF1. 사용자 관리 기능**
**WF1.1. 회원가입
WF1.1.1. 사용자는 회원가입 시 정보(아이디, 비밀번호, 닉네임 등)를 입력해야 한다.
WF1.1.2. 사용자는 기존 사용자와 중복되는 아이디를 사용할 수 없다.
WF1.2. 로그인
WF1.2.1. 사용자는 회원가입 시 등록한 아이디와 비밀번호로 로그인할 수 있다.
WF1.2.2. 사용자는 비밀번호 분실 시 본인 확인 후 비밀번호를 변경할 수 있다.
WF1.3. 마이페이지
WF1.3.1. 사용자는 이전 키워드 검색 기록을 확인할 수 있다.
WF1.3.2. 사용자는 찜한 도서 목록을 확인할 수 있다.**
WF2. 키워드를 이용한 도서 추천 기능
WF2.1. 키워드 검색
WF2.1.1. 연관 키워드 선호도 선택
WF2.1.1.1. 사용자는 본인이 입력한 키워드와 유사한 키워드를 확인할 수 있다.
WF2.1.1.2. 사용자는 시스템이 제공한 유사한 키워드 중 본인의 의도와 가까운 키워드(선호 키워드)를 추가로 선택할 수 있다.
WF2.2. 추천 도서 목록 확인
WF2.2.1. 사용자는 본인이 입력,선택한 키워드와 유사한 도서를 추천받을 수 있다.
WF2.2.2. 도서 찜하기
WF2.2.2.1. 사용자는 추천 도서 목록에서 마음에 드는 도서를 찜할 수 있다
WF2.2.2.2. 찜한 도서는 사용자 개인의 마이페이지에서 확인할 수 있다.
2-2 사용자 데이터 분석 기능 - UF
UF1. 시스템은 수집한 도서의 키워드 데이터를 TF-IDF모델을 이용하여 메트릭스를 만들고 사용자에게 입력받은 키워드를 TF-IDF에 넣고 유사 키워드를 추출한다.
UF2. 시스템은 TF-IDF에서 추출된 키워드와 연관성이 높은 도서를 찾고, E2E ASBA모델을 이용해 책의 리뷰의 키워드와 선호도를 분석하여 반환하여 제공한다.
UF3. 사용자는 제공된 유사 키워드의 선호도를 선택하고 선호도에따라 필터링한 도서들에 우선순위를 매긴 후 추천 도서 목록을 제공한다.

3. 비기능적 요구사항   
3-1 운영 환경에 대한 요구사항 - OR
OR1. 시스템은 안드로이드 운영체제에서 동작해야 한다.
**3-2 성능 요구사항 - PR**
**PR1. 시스템이 제공하는 도서 권수는 최소 20,000권으로 한다.**
3-3 보안 요구사항 - SR
SR1. 회원의 개인정보는 암호화한다.
3-4 문화 및 정책적 요구사항 - CR
CR1. 시스템의 출력은 한국어를 사용하여 출력되어야 한다.
CR2. 시스템의 시간은 한국 표준시(KST)를 따른다.

**우리 프로젝트의 요구사항 정의서 초안 일부입니다. 
굵은 글씨로 표시한 사용자 관리 기능(찜기능)이 추천 서비스 제공에 필요한 부분인지,
성능 요구사항의 시스템이 제공하는 도서의 정보량의 최소값이 적절한지 이야기하고싶습니다.
또한 추가하거나 수정해야하는 프로젝트의 요구사항도 말해주세요!**

**Comment by bebusl** [comment]
1. 개인적인 생각으로는 사용자 관리 기능이 있으면 좋을 것 같습니다!
프로젝트 진행 기간을 2달 반 정도로 생각하면 지금 생각하고 있는 검색/추천 기능은 충분히 구현할 수 있을 것 같고 사용자 관리 기능이 많이 복잡한 기능은 아니어서 충분히 구현은 가능하다고 생각합니다. 사용자 관리 기능이 있으면 서비스의 완성도가 좀 더 올라가 보일 것 같습니다.

2. 다른 이슈에 올라온 도서량을 보면 총 160만권 정도로 보이는데, 데이터 수집량을 총량의 30%정도로 한다면 160만권의 30%인 50만권 정도를 최소량으로 잡는 게 좋을 것 같습니다.
하지만 50만권도 크롤링하기 벅찬 양이라고 생각돼서 일단 문서상에서는 수치를 좀 낮춰서 10만권으로 기입해놓으면 어떨까 싶습니다!

3. 1.2.2 주요기능설명의 2번 내용이 조금 수정되어야 할 것같습니다.!(제가 잘못 이해하고 있는 부분 있으면 다시 수정해주세요!!)
저희 서비스 흐름이
1. 사용자가 키워드를 입력한다.
2. 입력한 키워드와 유사한 키워드를 찾는다.
3. 입력 키워드+유사한 키워드를 기반으로 추천할 책을 고른다(tf-idf 이용) => **여기서 이미 추천할 책 리스트는 정해져있음. 이 다음부터 추천 랭킹을 매기는 과정**
4. 추천할 책으로 걸러진 리스트의 리뷰를 가져와서 리뷰에서 키워드를 추출
5. 리뷰에서 추출된 키워드에서 사용자에게 선호 키워드를 선택해 최종적으로 랭킹을 매김

이런 식으로 진행되기 때문에, 유사한 키워드에서 선호 키워드를 선택하게 하는 것이 아닌 **리뷰에서 추출한 키워드**에서 선호 키워드를 선택하게 해 좀 더 사용자의 의도에 맞는 책을 추천할 수 있도록 한다고 하는 편이 맞는 것 같습니다.

**Comment by bebusl** [comment]
그리고 1.2.2 주요기능설명의 2번 내용이 조금 수정되어야 할 것 같습니다.!(제가 잘못 이해하고 있는 부분 있으면 다시 수정해주세요!!)
저희 서비스 흐름이
1. 사용자가 키워드를 입력한다.
2. 입력한 키워드와 유사한 키워드를 찾는다.
3. 입력 키워드+유사한 키워드를 기반으로 추천할 책을 고른다(tf-idf 이용) => **여기서 이미 추천할 책 리스트는 정해져있음. 이 다음부터 추천 랭킹을 매기는 과정**
4. 추천할 책으로 걸러진 리스트의 리뷰를 가져와서 리뷰에서 키워드를 추출
5. 리뷰에서 추출된 키워드에서 사용자에게 선호 키워드를 선택해 최종적으로 랭킹을 매김

이런 식으로 진행되기 때문에, 유사한 키워드에서 선호 키워드를 선택하게 하는 것이 아닌 **리뷰에서 추출한 키워드**에서 선호 키워드를 선택하게 해 좀 더 사용자의 의도에 맞는 책을 추천할 수 있도록 한다고 하는 편이 맞는 것 같습니다.

**Comment by leejeongeun0** [comment]
제공하는 도서 권수의 최소량은 10만권으로 하겠습니다.
주요기능설명의 내용에 상세부분이 명확하게 설명되지않아 오해의 소지가 있음을 확인했습니다. 이부분도 수정하겠습니다!
