### ISSUE TITLE
멘토링 내용 정리

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#11]
### 1차 멘토링

**긍/부정 키워드 추출 모델의 외래어 처리 이슈**

- 딥러닝 모델이 아닌 심플하게 모델 작성
- 외래어 처리를 잘하는 pretrained model을 사용

**2021.09.27**

**Comment by bebusl** [comment]
-프로젝트 외 질문 : 실습/이론 공부의 비중
답변 : 대학원을 갈거면 이론에 좀 더 비중을 두고 공부를 해도 된다. 취업을 위한 공부라면  취업 공고를 읽어보고, 코딩 인터뷰에 대응가능한 정도로 공부하기를 추천.

**Comment by leejeongeun0** [comment]
**2차 멘토링 (2021.11.12)**
 - 도서 추천 앱의 기대효과 및 발전방향
 추천서비스의 연관상품 판매 추천, 광고시장의 사이클, 앱 체류시간과 매출 등의 발전방향의 관해 상세하게 설명.
현재 작성된 기대효과가 문화적인 부분에 치우쳐저있음을 느끼고 상업적인 부분과 연동하여 발전할 수 있는 방향을 알게됨.

**Comment by bebusl** [comment]
2차 멘토링 내용 추가
 프로젝트 보고서에서 중점적으로 보는 부분(보강해야 할 점) - 찐 결과 보고서에서 추가하면 좋을 것 같음
 * 계획했던 바가 실제로 얼마나 이루어졌는가, 왜 이렇게 설계됐는가를 설명
 * 결과가 좋지 못했을 때 - 이유를 적는 것. 뭐든 간에 숫자로 정량적으로 표현할 수 있으면 좋다.
 *  수익성 관련된 성과를 기술하면 좋다.

**Comment by dungbik** [comment]
### 2차 멘토링

**시스템 구성도 개선점**

- 현재 시스템 구성도가 서비스에 맞게 잘 구성이 되어있다.
- 다만 쿠버네티스를 활용하여 서비스를 구성했을 때 비용적인 문제가 발생할 수 있다.

2021.11.12
