### ISSUE TITLE
수집할 서적의 수 결정

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#19]
### 카테고리 별로 1만권 씩 수집하여 전 처리 후 모델에 학습을 진행

- 27만권 -> 23만권
  - 중복되는 서적 제거
- numpy에서 메모리 부족 오류 발생
  - 중복되는 단어를 제거하여 배열의 크기를 줄여 해결
- 만든 모델 로딩 시간: 약 24초
- 결과 반환 시간: 약 0.3초

**가능하다면 모든 서적을 수집하고 싶지만 학습시 메모리 부족으로 인해 총 서적 수는 30만권 미만으로 잡아야 할 것 같습니다.**
**카테고리 별로 어느 정도의 서적을 수집하는 것이 좋을지 정해야 합니다.**

**Comment by dungbik** [comment]
|고유아이디|카테고리|서적 수|
|------|---|---|
|1230|가정/요리/뷰티|16,125|
|55890|건강/취미/레저|33,067|
|170|경제경영|66,403|
|2105|고전|16,899|
|987|과학|34,173|
|8257|대학교재/전문서적|192,926|
|2551|만화|37,709|
|4395|달력/기타|9,395|
|798|사회과학|76,241|
|1|소설/시/희곡|159,377|
|1383|수험서/자격증|135,647|
|1108|어린이|111,551|
|55889|에세이|53,104|
|1196|여행|13,868|
|74|역사|34,118|
|517|예술/대중문화|57,828|
|1322|외국어|43,190|
|13789|유아|66,746|
|656|인문학|63,523|
|336|자기계발|34,640|
|112011|장르소설|44,994|
|2913|잡지|68,978|
|17195|전집/중고전집|29,216|
|1237|종교/역학|100,208|
|2030|좋은부모|11,355|
|1137|청소년|21,641|
|351|컴퓨터/모바일|35,499|
|50246|초등학교참고서|45,544|
|76000|중학교참고서|28,852|
|76001|고등학교참고서|41,904|

---

### 2021.09.25 19:43

**Comment by leejeongeun0** [comment]
대학교재/전문서적,  잡지, 초.중.고 참고서 6개의 카테고리를 제외하고 각 카테고리에서 20%의 비율로 데이터를 수집하는건 어떨까 싶습니다. 20%씩 수집하였을때 총 서적 수는 약 25만권정도 될거같습니다.
몇몇개의 카테고리를 제외하고싶은 이유를 말씀드리면 대학교재/전문서적, 초.중.고 참고서의 경우 대부분 학교나 학원, 교과목에서 책을 지정하여 사용하기때문에 검색의 수요가 떨어진다고 생각합니다.
또한 잡지는 유명 잡지사들의 월간호가 계속적으로 출간되는형태이므로 추천서비스에 큰 역할이되지 못할거같기 때문입니다.

**Comment by bebusl** [comment]
권수가 좀 적은(1~6만권 사이) 카테고리는 10%, 6~만권을 가진 카테고리는 25%정도로 비율 조정하면 어떨까 싶습니다. 보유한 책 양이 많을 수록 좀 더 찾는 사람이 많을 것 같기도하고 내용이 좀 더 세분화된 카테고리일 가능성이 많기 때문입니다. 세분화된 카테고리일수록 데이터가 좀 더 많아야 좀 더 정확한 추천이 가능할 것 같습니다.

**Comment by dungbik** [comment]
**의견을 종합해서**

- 대학교재/전문서적, 잡지, 초.중.고 참고서 제외
- 6만권 이상 카테고리 25%, 미만 20%

|고유아이디|카테고리|서적 수|수집 수|
|------|---|---|---|
|1230|가정/요리/뷰티|16,125|3200|
|55890|건강/취미/레저|33,067|6600|
|170|경제경영|66,403|16600|
|2105|고전|16,899|3300|
|987|과학|34,173|6800|
|2551|만화|37,709|7500|
|798|사회과학|76,241|19000|
|1|소설/시/희곡|159,377|39800|
|1383|수험서/자격증|135,647|33900|
|1108|어린이|111,551|27800|
|55889|에세이|53,104|10600|
|1196|여행|13,868|3400|
|74|역사|34,118|6800|
|517|예술/대중문화|57,828|11500|
|1322|외국어|43,190|8600|
|13789|유아|66,746|16600|
|656|인문학|63,523|15800|
|336|자기계발|34,640|6900|
|112011|장르소설|44,994|9000|
|1237|종교/역학|100,208|25000|
|2030|좋은부모|11,355|2200|
|1137|청소년|21,641|4300|
|351|컴퓨터/모바일|35,499|7100|

**Comment by dungbik** [comment]
**의견을 다시 종합해서 아래처럼 하는 건 어떤가요?**

- 잡지, 초.중.고 참고서 제외
- 6만권 이상 카테고리 25%, 미만 20%
- 총 340,300권

|고유아이디|카테고리|서적 수|수집 수|
|------|---|---|---|
|1230|가정/요리/뷰티|16,125|3,200|
|55890|건강/취미/레저|33,067|6,600|
|170|경제경영|66,403|16,600|
|2105|고전|16,899|3,300|
|987|과학|34,173|6,800|
|8257|대학교재/전문서적|192,926|48,000|
|2551|만화|37,709|7,500|
|798|사회과학|76,241|19,000|
|1|소설/시/희곡|159,377|39,800|
|1383|수험서/자격증|135,647|33,900|
|1108|어린이|111,551|27,800|
|55889|에세이|53,104|10,600|
|1196|여행|13,868|3,400|
|74|역사|34,118|6,800|
|517|예술/대중문화|57,828|11,500|
|1322|외국어|43,190|8,600|
|13789|유아|66,746|16,600|
|656|인문학|63,523|15,800|
|336|자기계발|34,640|6,900|
|112011|장르소설|44,994|9,000|
|1237|종교/역학|100,208|25,000|
|2030|좋은부모|11,355|2,200|
|1137|청소년|21,641|4,300|
|351|컴퓨터/모바일|35,499|7,100|

### 이렇게 하는 것으로 확정되면 수집을 다시 진행하겠습니다.
