### ISSUE TITLE
프로젝트 역할 배분

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#2]
### 필요한 역할

- FrontEnd
- BackEnd(API Server + DB)
- Model

**본인이 익숙한 언어와 그동안 해본 프로젝트(했던 역할포함)의 간략한 설명과 원하는 역할을 적어주세요!**

**Comment by dungbik** [comment]
**익숙한 언어**

- Java(Kotlin)
- Python
- JavaScript
- C++

**그동안 해본 프로젝트**

- 교내 알고리즘 대회용 채점 시스템 (Judger를 할용한 채점 시스템 개발)
- 머신러닝 기반 강의 추천 시스템 (기능 서버와 DB 메인 /프론트엔드부분과 모델을 합쳐 최종본 완성)
- Mutation Signature 분석 Tool 제작 (Web, API Server, DB)

**Comment by bebusl** [comment]
익숙한 언어
JavaScript
Python
C++

그동안 해본 프로젝트
충북대학교 튜터링 시스템 - 프론트엔드
포켓폴리스(앱) - 앱과 실시간 사용자 추적 지도를 보여주는 웹 구현
PSA : 리뷰 키워드 기반 상품 추천 시스템 -벡엔드(api 서버 및 카프카 연동 등), 프론트엔드

원하는 역할 : Nodejs기반 백엔드

**Comment by bytecell** [comment]
정영섭Prof: 훌륭합니다. assignee 지정을 잘 하고 있는 것 같습니다.

참고로,
나중에 개발 과정에 돌입했을 때에는,
해당 이슈에 논의에 정말로 참여해야 하는 당사자들과, 개발에 참여한 사람들만으로 assign 해야 합니다-.

**Comment by leejeongeun0** [comment]
익숙한 언어

Java
C++

그동안 해본 프로젝트

데이트코스 추천(앱) - 프론트앤드,

원하는 역할 : frontend
