### ISSUE TITLE
서비스 평가 방식 선정

### ISSUE THREAD

**Issue by bebusl** [bebusl/Industrial-Project#20]
1. 정확도 평가 - 대강X, 구체적으로 어떻게 정확도를 계산할 건지 필요
2. 사용자 평가(혹은 설문 평가)
등 서비스를 평가할 수 있는 지표를 만들어야 함.

교수님 예시 ) 넷플릭스
추천 영상에 대해 좋아요/쏘쏘/싫어요로 평가하게 함 -> 그 수치에 기반해 얼마나 잘 추천됐는지 평가

유사한 타 서비스와 비교가 가능하면 더 좋음.
-발표 시 어떤 모델을 사용하는지 구체적 설명하지말고, 모델 이름만 말하라고 하셨음. 

**어떤 방식으로 평가하면 좋을지** 의견 공유해주세요

**Comment by dungbik** [comment]
**개인적으로 추천 모델의 정량적 평가는 힘들고 의미가 없다고 생각합니다**
**평가를 한다면 넷플릭스처럼 좋다/나쁘다 평가한 수치를 기반하여 평가를 하는 것이 좋다고 생각합니다**

**Comment by leejeongeun0** [comment]
사용자가 키워드를 검색한 후 제공되는 추천도서목록을 보고 별점을 부여해 평가를 받는것이  좋다고 생각합니다. 
혹은 도서 찜하기 서비스를 제공하는 만큼 추천 도서 목록 중 한개 이상의 도서에 찜하기를 한 사용자는 만족도가 높다는 것으로 판단하고, 찜하기를 하지않은 사용자는 만족도가 낮다고 판단하여 이를 평가지표로 사용하는 방법도 생각해보았습니다.

**Comment by bebusl** [comment]
추천리스트 5순위까지의 추천 만족도를 사용자에게 입력(좋음/중도/나쁨)받아 평가받는 게 좋을 것 같습니다. 사용자-항목 쌍에 대한 예측 평점(rating)과 실제 평점간의 차이(오차)를 통해 수치화할 수 있을 것 같습니다.

**Comment by bebusl** [comment]
세 명 다 사용자 평가에 기반해서 성능 평가가 이루어졌다는 의견은 같아서 성능 평가는 사용자 평가 기반으로 하는 것으로 하겠습니다.
혹시 구체적으로 수치화를 할 방법이 있다면 의견 공유해주시면 감사하겠습니다!

**Comment by dungbik** [comment]
### 교수님이 주신 예시

- 10사람에 대하여 기존 서비스(예: Naver 평점 기반으로 sorting된 결과)로 추천된 카페 3곳에 각각 방문하여 평점 정보를 매기기 (평점 정보 수집은 별도 구글 설문 등을 통해 받기)
- 동일한 10사람에 대하여 우리팀 서비스로 추천된 카페 3곳에 각각 방문하여 평점 정보 매기기 (동일한 방식)
위처럼 수행한 후, 평점 정보 비교.
설문지 질문을 다양한 측면에서 분석할 수 있도록 잘 만드는 게 좋을 겁니다.

**Comment by bebusl** [comment]
우선 사용자에게 서비스 평가를 받고 (1점~5점) 평가 점수의 평균을 매길 예정입니다. 타 서비스도 동시에 평가 받아서 두 점수를 비교하면 좋을 것 같습니다.
