### ISSUE TITLE
서적 데이터 수집기 속도 느림

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#25]
**수집기 속도 느린 원인**

- Selenium을 이용한 동적 크롤링 방식

**해결 방안**

1. 수집기를 여러 개 실행하여 동시에 수집 진행
2. 정적 크롤링 방식으로 변경

**해결 방안의 어려운 점**

- 1번 방식의 경우 웹 드라이버를 여러 개 실행해야 하는데 같은 네트워크를 통해 통신을 하기 때문에 응답이 느릴 때가 종종 생겨서 이에 대한 예외 처리 혹은 재시도 기능을 구현해야 합니다.
- 2번 방식의 경우 알라딘의 웹 방식이 스크롤을 내렸을 때 내용이 생기는 것이라 이때 요청되는 부분을 분석해서 구현해야 하는 것이 어렵습니다.

**수집해야 할 데이터가 바뀔 수도 있고 많아지거나 적어질 수 도 있는데, 이 때마다 수집을 새로해야 하기 때문에 수집기의 속도를 올려야 합니다.**

**Comment by bytecell** [comment]
^^
