### ISSUE TITLE
6주차 프로젝트 진행사항 공유

### ISSUE THREAD

**Issue by bebusl** [bebusl/Industrial-Project#29]
서버 : 이진희
모델 : 윤정환
앱 : 이정은

각자 맡은 부분에 대한 진행사항을 매주 알려주세요!
이번주에 한 부분, 다음주 계획 적어주시면 될 것 같습니다.

**Comment by dungbik** [comment]
**이번 주**

- 정적 서적 데이터 수집기 구현
- 서적 추천 모델 학습 구현
- 서적 데이터 전처리기 보완 (중복 데이터 제거)

**다음 주**

- 서적 카테고리 별 수집 수 정해지면 그거대로 다시 서적 데이터 수집
- 정적 리뷰 데이터 수집기 구현
- 리뷰 데이터 긍/부정 키워드 라벨링 툴 구현

**Comment by bebusl** [comment]
이번 주
* api서버 - 로그인 관련 api 작성중
* api서버 - 전체 db 구조 구축

다음주
* 찜 기능 api 구현
* 모델 서버 구상
