### ISSUE TITLE
모델 설계

### ISSUE THREAD

**Issue by leejeongeun0** [bebusl/Industrial-Project#3]
**모델 구체화에 대한 정보**

 **- 서비스에 적용할 모델.**
 (만약 모델이 없을 시 모델 제작에 필요한 데이터와 제작방법.)
 **- 필요한 데이터 , 사용할 테이터**
 (만약 데이터가 없을 시 가공해야 할 데이터 위치나 주소, 형식.)

**Comment by leejeongeun0** [comment]
데이터 자료조사 내용
-	청주시 음식점 : https://www.data.go.kr/data/3033595/fileData.do
-	연령별 권장 열량: https://www.data.go.kr/data/15050017/fileData.do
-       음식 영양소 칼로리: https://www.data.go.kr/data/15050018/fileData.do
-

**Comment by dungbik** [comment]
**Hybrid Recommend System (Contents-based + Collaborative Filtering)**

- 수많은 음식점에 대한 정보를 토대로 데이터를 가공하기 힘듦
- 데이터가 하나로 정리되어 있지 않아서 병합을 해야하며, 정보가 부족한 음식점이 많음

딥 러닝 기반의 추천을 하더라도 위의 문제점은 똑같이 발생
