### ISSUE TITLE
7주차 프로젝트 진행사항 공유

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#34]
**각자 맡은 부분에 대한 진행 사항을 알려주세요!**
**이번 주에 한 부분, 다음 주 계획 적어주시면 될 것 같습니다.**

### 이번 주 진행 계획
**이정은**
- 비밀번호 분실 화면(본인인증->비밀번호 변경) 구현예정

**윤정환**
- 서적 카테고리 별 수집 수 정해지면 그거대로 다시 서적 데이터 수집
- 정적 리뷰 데이터 수집기 구현
- 리뷰 데이터 긍/부정 키워드 라벨링 툴 구현

**이진희**
- 찜 기능 api 구현
- 모델 서버 구상

**Comment by dungbik** [comment]
**이번주**

- 정적 리뷰 데이터 수집기 구현
- 도서 추천 모델 추천 구현

**Comment by bebusl** [comment]
저번주 :
* db schema작성 완료
* auth api 작성 완료

이번주
* 찜 기능 api 작성 중
