### ISSUE TITLE
랭킹 알고리즘 로직

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#48]
### 생각해야 할 것

- 부정의 리뷰도 반영되게 공식이 구성되어야 함
- 유의미한 결과가 나와야 함

**Comment by dungbik** [comment]
**도서의 키워드 벡터를 만들 때 0, 1로 하는 것이 아닌 전체 리뷰 수 대비 긍정의 비율을 사용**

**Comment by bebusl** [comment]
* 선택하는 것은 긍정적인 리뷰만.
* 키워드 벡터 : 전체 리뷰 수 대비 긍정의 비율
* 선택한 키워드의 우선순위 반영해야 함. (최대 5순위) 우선순위 반영 -> 1 - {우선순위}/{선택한 키워드 개수]를 키워드 벡터값에 곱해주는 것을 생각해봄.
