### ISSUE TITLE
추천 알고리즘 우선순위 적용 문제

### ISSUE THREAD

**Issue by bebusl** [bebusl/Industrial-Project#52]
현재 키워드 벡터와 사용자가 선택한 키워드 벡터간의 코사인 유사도를 통해 랭킹을 매겼음.

원래 선택 키워드에 관해 가중치를 곱해서 우선순위를 랭킹에 반영하려고 했으나
단순 값 조정으로는 우선순위를 정상적으로 반영하기 힘듦.

우선순위 반영 방법을 좀 더 생각해봐야 할 것 같음.

**Comment by dungbik** [comment]
**일단 가중치로 하는 것으로 하고, 이 값은 실제 테스트를 통해 정하도록 합시다.**
