### ISSUE TITLE
프로젝트 관리 방법

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#6]
**저희가 이번 솔루션을 진행하게 되면 크게 나누었을 때 최종 결과물로 아래와 같은 프로젝트들이 나옵니다.**

- Android App
- API Server
- Model Server

**이를 루트에서 모두 관리하는 것을 불편하다고 생각이 들기 때문에 분리를 하기 좋은 방법을 정하고 싶습니다.
제가 생각한 방법은 아래와 같습니다. 다른 방안이 있다면 편하게 올려주세요!**

1. 프로젝트 별로 레포를 파서 Submodule로 연결
2. 폴더로 한번 래핑해서 코드를 작성하고 브랜치로 구분

**Comment by dungbik** [comment]
교수님께서 ﻿"기업에서 한 팀에 소속된 사람들끼리 일할 때의 방식에 기반하여 배점이 잡혀있다" 라고 하셔서 1번 방법은 빼야할 것 같습니다.

**Comment by bebusl** [comment]
2번으로하고 각자 브랜치 적절하게파서 해야할 것 같습니다.
브랜치이름 Feature/기능이름인데 기능이름 적을 때 어떤 파트인지 적는것도 좋을 것 같습니다.
(ex. feature/front_login, feature/front/login)

**Comment by dungbik** [comment]
최종 솔루션이 나올 때, 마스터 브랜치에 합쳐야 하기 때문에 기능 이름으로 서브 폴더를 만든 후 그 안에서 작업을 하는 것이 좋을 것 같습니다.

**Comment by leejeongeun0** [comment]
기능 이름별로 서브폴더를 만들어서 작업하는 방법이 구별에도 병합에도 좋은 방법인거 같습니다.

**Comment by dungbik** [comment]
### 프로젝트를 폴더로 래핑하고 어떤 기능인지 브랜치로 구분하는 것으로 진행합시다!
