### ISSUE TITLE
수집할 서적의 범위 설정

### ISSUE THREAD

**Issue by dungbik** [bebusl/Industrial-Project#7]
### 알라딘에서 모든 서적을 수집하기는 힘들 것 같아서 범위를 정해서 진행해야 할 것 같습니다.

**알라딘에서 서적 데이터를 수집할 때 아래와 같은 EndPoint로 접근하여 크롤링을 할 예정입니다.**

- https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=277945463
- ItemId에 값을 대입하여 해당 서적의 데이터를 수집할 것입니다.
- ItemId는 1부터 시작되며 최근 것일 수록 숫자가 커집니다.
- 이 숫자의 범위를 정하면 좋을 것 같습니다.

**Comment by dungbik** [comment]
**위의 설명처럼 ItemId의 범위를 임의로 정해서 크롤링을 수행하니 중고, POD, 수입 서적등 특수 서적이 많이 포함되어 있어 크롤링 시간이 너무 오래 걸리는 문제가 발생합니다.**
**따라서 국내 서적을 카테고리 별로  판매량에 따라 정렬하여 x권 만큼 수집을 해야 할 것 같습니다.**
**카테고리 별로 총 권 수를 정리해서 올려두겠습니다. 같이 몇 권씩 수집할지 정하는 것을 도와주시면 감사하겠습니다!**

**Comment by dungbik** [comment]
|제목|내용|설명|
|------|---|---|
|테스트1|테스트2|테스트3|
|테스트1|테스트2|테스트3|
|테스트1|테스트2|테스트3|

**Comment by dungbik** [comment]
**아래 카테고리는 없어도 될 것 같습니다.**

- 달력/기타 (서적이 아님)
- 전집/중고전집 (여러 서적을 묶은 세트 상품이 대부분임)

**Comment by bebusl** [comment]
학습/검증 단계까지는 일단 1000권씩 수집해서 사용하고, 실제 서비스 적용시에는 카테고리별 총량의 30%정도를 크롤링해서 사용할 것 좋을 것 같습니다.
대학교재/카테고리에 10만권이 있다고 하면 3만권,
인문 카테고리에 5만권이 있다고 하면 1.5만권을 크롤링하는 식으로 모든 카테고리에서 균일한 권수를 긁어오기 보다는 총량에 비례해서 가져오는 식으로 하는 편이 좋을 것 같습니다.

**Comment by dungbik** [comment]
**데이터 수집, 모델 학습 시간을 확인해보면서 최대한 많은 책들을 데이터로써 사용하는 것이 좋을 것 같습니다.**

- 시작을 카테고리 별 총량의 30%로 하고 테스트를 해보며 최적치를 찾아보는 것이 좋을 것 같습니다.

**Comment by leejeongeun0** [comment]
테스트하면서 데이터양을 조절할때 비인기 카테고리를 우선순위로 줄이고, 인기 카테고리 비율을 우선순위로 늘리면 좋겠습니다. 인기, 비인기 기준은 전체 베스트셀러에 올라온 도서의 카테고리 빈도수로 하면 좋을거 같습니다.

**Comment by dungbik** [comment]
**그러면 일단 학습 시간 확인 및  검증을 위해 카테고리 별로 1000권씩 데이터를 수집하겠습니다.**
